/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.CardLayout;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;

/**
 *
 * @author Ashada
 */
public class SelectCharaFS extends javax.swing.JFrame {

    /**
     * Creates new form SelectCharaBtn
     */
    public SelectCharaFS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgPanel = new javax.swing.JPanel();
        yaeLB = new javax.swing.JLabel();
        yoimiyaLB = new javax.swing.JLabel();
        ayakaLB = new javax.swing.JLabel();
        btnpanel = new javax.swing.JPanel();
        yaebtn = new javax.swing.JButton();
        yoimiyabtn = new javax.swing.JButton();
        ayakabtn = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Select Your Character");
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        imgPanel.setLayout(new java.awt.CardLayout());

        yaeLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        yaeLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/yae.jpg"))); // NOI18N
        imgPanel.add(yaeLB, "2");

        yoimiyaLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        yoimiyaLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/yoimiya.jpg"))); // NOI18N
        imgPanel.add(yoimiyaLB, "1");

        ayakaLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ayakaLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/ayaka.jpg"))); // NOI18N
        imgPanel.add(ayakaLB, "0");

        getContentPane().add(imgPanel, java.awt.BorderLayout.CENTER);

        yaebtn.setText("Yae");
        yaebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yaebtnActionPerformed(evt);
            }
        });
        btnpanel.add(yaebtn);

        yoimiyabtn.setText("Yoimiya");
        yoimiyabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yoimiyabtnActionPerformed(evt);
            }
        });
        btnpanel.add(yoimiyabtn);

        ayakabtn.setText("Ayaka");
        ayakabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayakabtnActionPerformed(evt);
            }
        });
        btnpanel.add(ayakabtn);

        exitbtn.setText("Exit");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });
        btnpanel.add(exitbtn);

        getContentPane().add(btnpanel, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitbtnActionPerformed

    private void ayakabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayakabtnActionPerformed
        // TODO add your handling code here:
        CardLayout c1 = (CardLayout)(imgPanel.getLayout());
        c1.show(imgPanel, "0");
    }//GEN-LAST:event_ayakabtnActionPerformed

    private void yoimiyabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yoimiyabtnActionPerformed
        // TODO add your handling code here:
        CardLayout c1 = (CardLayout)(imgPanel.getLayout());
        c1.show(imgPanel, "1");
    }//GEN-LAST:event_yoimiyabtnActionPerformed

    private void yaebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yaebtnActionPerformed
        // TODO add your handling code here:
        CardLayout c1 = (CardLayout)(imgPanel.getLayout());
        c1.show(imgPanel, "2");
    }//GEN-LAST:event_yaebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectCharaFS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectCharaFS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectCharaFS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectCharaFS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SelectCharaFS fullFrame = new SelectCharaFS();
                GraphicsDevice device =
                        GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
                device.setFullScreenWindow(fullFrame);
                fullFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ayakaLB;
    private javax.swing.JButton ayakabtn;
    private javax.swing.JPanel btnpanel;
    private javax.swing.JButton exitbtn;
    private javax.swing.JPanel imgPanel;
    private javax.swing.JLabel yaeLB;
    private javax.swing.JButton yaebtn;
    private javax.swing.JLabel yoimiyaLB;
    private javax.swing.JButton yoimiyabtn;
    // End of variables declaration//GEN-END:variables
}
