/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penampilgambar;

import java.awt.CardLayout;

/**
 *
 * @author Ashada
 */
public class SelectCharaBtn extends javax.swing.JFrame {

    /**
     * Creates new form SelectCharaBtn
     */
    public SelectCharaBtn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new javax.swing.JPanel();
        btnpanel = new javax.swing.JPanel();
        yaebtn = new javax.swing.JButton();
        yoimiyabtn = new javax.swing.JButton();
        ayakabtn = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();
        imgPanel = new javax.swing.JPanel();
        yaeLB = new javax.swing.JLabel();
        yoimiyaLB = new javax.swing.JLabel();
        ayakaLB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Select Your Character");

        bgPanel.setBackground(new java.awt.Color(255, 255, 255));

        btnpanel.setBackground(new java.awt.Color(255, 255, 255));

        yaebtn.setText("Yae Miko");
        yaebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yaebtnActionPerformed(evt);
            }
        });
        btnpanel.add(yaebtn);

        yoimiyabtn.setText("Yoimiya");
        yoimiyabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yoimiyabtnActionPerformed(evt);
            }
        });
        btnpanel.add(yoimiyabtn);

        ayakabtn.setText("Kamisato Ayaka");
        ayakabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayakabtnActionPerformed(evt);
            }
        });
        btnpanel.add(ayakabtn);

        exitbtn.setText("Exit");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });
        btnpanel.add(exitbtn);

        imgPanel.setLayout(new java.awt.CardLayout());

        yaeLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penampilgambar/yae.jpg"))); // NOI18N
        imgPanel.add(yaeLB, "2");

        yoimiyaLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penampilgambar/yoimiya.jpg"))); // NOI18N
        imgPanel.add(yoimiyaLB, "1");

        ayakaLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penampilgambar/ayaka.jpg"))); // NOI18N
        imgPanel.add(ayakaLB, "0");
        ayakaLB.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout bgPanelLayout = new javax.swing.GroupLayout(bgPanel);
        bgPanel.setLayout(bgPanelLayout);
        bgPanelLayout.setHorizontalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addComponent(imgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        bgPanelLayout.setVerticalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitbtnActionPerformed

    private void ayakabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayakabtnActionPerformed
        // TODO add your handling code here:
        CardLayout c1 = (CardLayout)(imgPanel.getLayout());
        c1.show(imgPanel, "0");
    }//GEN-LAST:event_ayakabtnActionPerformed

    private void yoimiyabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yoimiyabtnActionPerformed
        // TODO add your handling code here:
        CardLayout c1 = (CardLayout)(imgPanel.getLayout());
        c1.show(imgPanel, "1");
    }//GEN-LAST:event_yoimiyabtnActionPerformed

    private void yaebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yaebtnActionPerformed
        // TODO add your handling code here:
        CardLayout c1 = (CardLayout)(imgPanel.getLayout());
        c1.show(imgPanel, "2");
    }//GEN-LAST:event_yaebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectCharaBtn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectCharaBtn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectCharaBtn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectCharaBtn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectCharaBtn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ayakaLB;
    private javax.swing.JButton ayakabtn;
    private javax.swing.JPanel bgPanel;
    private javax.swing.JPanel btnpanel;
    private javax.swing.JButton exitbtn;
    private javax.swing.JPanel imgPanel;
    private javax.swing.JLabel yaeLB;
    private javax.swing.JButton yaebtn;
    private javax.swing.JLabel yoimiyaLB;
    private javax.swing.JButton yoimiyabtn;
    // End of variables declaration//GEN-END:variables
}
